CREATE DATABASE IF NOT EXISTS beoLife
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_unicode_ci;

USE beoLife;

CREATE TABLE IF NOT EXISTS events (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	category VARCHAR(100) NOT NULL,
	date DATETIME NOT NULL,
	location VARCHAR(255),
	price DECIMAL(10, 2),
	image_url TEXT,
	link TEXT
);

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	lastname VARCHAR(40) NOT NULL,
	username VARCHAR(40) NOT NULL UNIQUE,
	email VARCHAR(120) NOT NULL UNIQUE,
	avatar_url VARCHAR(255) NULL,

	CHECK (CHAR_LENGTH(TRIM(username)) BETWEEN 3 AND 40),
	CHECK (CHSAR_LENGTH(TRIM(email)) >0)
);

CREATE TABLE IF NOT EXISTS saved_events(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL UNIQUE,
	event_id INT NOT NULL UNIQUE,

	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);

