CREATE DATABASE IF NOT EXISTS beoLife
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_unicode_ci;

USE beoLife;

CREATE TABLE IF NOT EXISTS events (
	id INT AUTO_INCREMENT PRIMARY KEY,
	event_title VARCHAR(255) NOT NULL,
	event_description TEXT,
	category VARCHAR(100) NOT NULL,
	event_date DATETIME NOT NULL,
	event_location VARCHAR(255),
	event_price DECIMAL(10, 2),
	event_image_url TEXT,
	event_link TEXT
);

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	lastname VARCHAR(40) NOT NULL,
	username VARCHAR(40) NOT NULL UNIQUE,
	email VARCHAR(120) NOT NULL UNIQUE,
	avatar_url VARCHAR(255) NULL,

	CHECK (CHAR_LENGTH(TRIM(username)) BETWEEN 3 AND 40),
	CHECK (CHAR_LENGTH(TRIM(email)) >0)
);

CREATE TABLE IF NOT EXISTS saved_events(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	event_id INT NOT NULL,

	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,

	UNIQUE(user_id, event_id)
);

